Sprint 2
arigatory/middle.messenger.praktikum.yandex pull request #4
Opened 2022-09-12 05:48 UTC by arigatory

2022-09-12 18:52 UTC, deadem commented
Привет!

Решение понравилось, грамотно разбито на компоненты, очень хорошо использованы типы. Но принять не могу, так как к сборке не подключены линтеры кода, а при ручном запуске линтеры ругаются на ошибки. Возвращаю для исправления ошибок, про которые сообщают линтеры, и включение их в процесс сборки.

Ниже несколько общих замечаний.

2022-09-12 18:52 UTC, deadem commented
* Некоторые файлы с исходным кодом не заканчиваются переводом строки. Вот тут можно почитать, почему это важно: https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

Проще всего это сделать, настроив .editorconfig с правилом `insert_final_newline = true` чтобы не следить руками за тем, чтобы файлы заканчивались правильно.

2022-09-12 18:53 UTC, deadem commented
* К сборке проекта не подключены линтеры. При запуске линтеров из консоли выводятся ошибки:

eslint: `node_modules\.bin\eslint.cmd **/*.ts`

```
src\index.ts
  14:1   error  More than 1 blank line not allowed                     no-multiple-empty-lines
  26:1   error  This line has a length of 104. Maximum allowed is 100  max-len
  26:48  error  A space is required after '{'                          @typescript-eslint/object-curly-spacing
  26:92  error  A space is required before '}'                         @typescript-eslint/object-curly-spacing
  27:9   error  Multiple spaces found before 'if'                      no-multi-spaces
  29:9   error  Multiple spaces found before 'if'                      no-multi-spaces

src\models\Model.ts
  37:1  error  More than 1 blank line not allowed       no-multiple-empty-lines
  41:4  error  Block must not be padded by blank lines  padded-blocks
  43:1  error  More than 1 blank line not allowed       no-multiple-empty-lines

src\models\Registration.ts
  35:21  error  Missing trailing comma  @typescript-eslint/comma-dangle

src\utils\validation.ts
    3:7   error  'hasWhiteSpace' was used before it was defined                                                         @typescript-eslint/no-use-before-define
    6:7   error  'onlyDigits' was used before it was defined                                                            @typescript-eslint/no-use-before-define
    9:8   error  'allowedLength' was used before it was defined                                                         @typescript-eslint/no-use-before-define
...

✖ 63 problems (60 errors, 3 warnings)
  31 errors and 0 warnings potentially fixable with the `--fix` option.
```

stylelint: `node_modules\.bin\stylelint.cmd **/*.*css`
```
src\css\_mixin.scss: When linting something other than CSS, you should install an appropriate syntax, e.g. "postcss-scss", and use the "customSyntax" option
src\css\common.scss: When linting something other than CSS, you should install an appropriate syntax, e.g. "postcss-scss", and use the "customSyntax" option
...
src/css/_variables.scss
 1:1  ✖  Expected $ variable name to match specified pattern  scss/dollar-variable-pattern
 2:1  ✖  Expected $ variable name to match specified pattern  scss/dollar-variable-pattern
 3:1  ✖  Expected $ variable name to match specified pattern  scss/dollar-variable-pattern
 4:1  ✖  Expected $ variable name to match specified pattern  scss/dollar-variable-pattern
 5:1  ✖  Expected $ variable name to match specified pattern  scss/dollar-variable-pattern

5 problems (5 errors, 0 warnings)
```

typescript: `node_modules\.bin\tsc`
```
src/app.ts:1:17 - error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

1 const express = require('express');
                  ~~~~~~~

src/app.ts:4:14 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

4 const PORT = process.env.PORT || 3000;
               ~~~~~~~

Found 2 errors in the same file, starting at: src/app.ts:1
```

2022-09-12 18:56 UTC, deadem commented
* На странице профиля не работают ссылки "изменить данные", "изменить пароль"

2022-09-12 19:04 UTC, deadem commented
* `в _mixin.scss`, видимо, опечатка: или 100% или 100px?
```
  height: 100%px;
```

2022-09-12 19:06 UTC, deadem commented
* выглядит как опечатка: __title добавился не к блоку, а к ребёнку `textarea:focus`:

```
  flex-direction: column;
  textarea:focus
```

https://github.com/arigatory/middle.messenger.praktikum.yandex/blob/ef23ec7c8d3ea631d6e7107e06f5c36551d7535e/src/utils/layout/add-user/add-user.scss#L8

2022-09-12 19:16 UTC, deadem requested changes

2022-09-12 19:16 UTC, deadem commented on package.json
>    "name": "chat",
**Никогда** не удаляйте package-lock.json из репозитория! Он нужен чтобы фиксировать конкретные номера установленных зависимостей, чтобы при разворачивании в "боевом" окружении устанавливались в точности те же версии пакетов, что и при разработке.

2022-09-12 19:16 UTC, deadem commented on src/app.ts
> +// app.set('view engine', 'pug');
Лучше сразу избавляться от закомментированного кода и не допускать его в проекте. Старые версии пусть хранятся в репозитории, а не в комментариях.

2022-09-12 19:16 UTC, deadem commented on src/index.html
> +<html lang="en">
Сообщения на сайте написаны по-русски, а в заголовках указано, что сайт на английском. И то же самое в шаблонах: `html(lang="en")`. Некоторые устройства могут постоянно предлагать перевести сайт на русский, что будет раздражать пользователя. Такое лучше сразу заменить во всём проекте на `ru`.

2022-09-12 19:16 UTC, deadem commented on src/utils/validation.ts
> +  return /\s/g.test(s);
* Регулярные выражения в валидации с небольшими недочётами:

тут нет необходмости в глобальном матчинге: нас устроит и единственное совпадение:
`return /\s/.test(s);`

2022-09-12 19:16 UTC, deadem commented on src/utils/validation.ts
> +  return /.*[A-ZА-Я].*/g.test(s);
Тут нет нужды ещё и в `.*` - test ищет совпадения в любом месте строке. Без `.*` будет чище и быстрее.
А ещё тут потерялась буква Ё - в юникоде она находится не в диапазоне между А-Я и её нужно указывать отдельно.

2022-09-12 19:16 UTC, deadem commented on src/utils/validation.ts
> +  return /.*[0-9].*/g.test(s);
Тут тоже не нужны g и `.*`:

2022-09-12 19:16 UTC, deadem commented on src/utils/validation.ts
> +  return /^[^@]+@[^@]+$/.test(s);
* Почти полностью повторяет `hasOneAt`, непонятно, зачем нужны две функции для, по сути, одного и того же:

2022-09-12 19:16 UTC, deadem commented on src/utils/validation.ts
> +  return /^[^@]*@[^@]+[\.]/.test(s);
* В квадратных скобках точка не экранируется - там она обозначает просто точку. Поэтому тут или обратный слеш не нужен, или квадратные скобки

2022-09-12 19:16 UTC, deadem commented on src/utils/validation.ts
> +  return /^.*[\.]$/.test(s);
* Тут можно просто: `/\.$/`

2022-09-12 19:16 UTC, deadem commented on src/utils/validation.ts
> +  return /^(\s*)?(\+)?([- _():=+]?\d[- _():=+]?){10,14}(\s*)?$/.test(s);
* А тут повтор проверок: `\s*` заматчит 0+ пробелов, поэтому `?` после `(\s*)` не нужен

2022-09-12 19:16 UTC, deadem commented on src/views/ChatDetailView/ChatDetailView.ts
> +  // eslint-disable-next-line class-methods-use-this
Предлагаю не бороться с линтером, вставляя в разные места выключение этого предупреждения, а выключить это правило целиком в eslint, раз вам пользы от него никакой, а только затыкать приходится.

2022-09-12 19:16 UTC, deadem commented on src/views/MessageInputView/MessageInputView.scss
> +  ::placeholder {
Наверное ::placeholder должен быть внутри input?

2022-09-12 19:16 UTC, deadem commented on src/views/LoginView/LoginView.ts
> +      this.parent.querySelector('.login-card__login-input')
Чуть-чуть не дожали: тут бы в шаблонах декларативно описывать подключаемые обработчики, а не в коде селекторами их искать... Но настаивать не буду.

2022-09-12 19:16 UTC, deadem commented on src/views/MainView/MainView.ts
> +  // onSelectedChatChanged(chat: Chat): void {
И вот этот закомментированный кусочек бы убрать...

2022-09-13 03:05 UTC, arigatory commented on src/views/LoginView/LoginView.ts
> +      this.parent.querySelector('.login-card__login-input')
Согласен. Я сначала так сделал, но терялся фокус при перерисовке страниц после ввода каждого символа. Решил, что в будущем лучше вынести инпут с подсветкой ошибок в отдельных компонент

2022-09-13 07:21 UTC, deadem approved these changes
Есть небольшие замечания, и при прогоне стайллинт ругается, что хочет кастомных правил, но в целом всё работает. Принято!

Успехов!

2022-09-13 07:21 UTC, deadem commented on .stylelintrc.json
> +    "scss/dollar-variable-pattern": ["^foo", { "ignore": "global" }],
Непонятно, зачем нужно это правило, если его прихоится выключать. Убрать его, да и всё...

2022-09-13 07:21 UTC, deadem commented on src/utils/validation.ts
> +const onlyDigits = (s: string): boolean => /^\d+$/g.test(s);
Тут тоже g лишняя: 
https://learn.javascript.ru/regexp-introduction#poisk-str-match

`.test` предназначен для поиска единственного совпадения, поэтому `g` тут не делает ничего.

2022-09-13 07:21 UTC, deadem commented on src/utils/validation.ts
> +const allowedChars = (s: string): boolean => /^[a-zA-Z0-9_-\s]*$/g.test(s);
...и тут

2022-09-13 07:21 UTC, deadem commented on src/utils/validation.ts
> +  /^[a-zA-Zа-яА-Я-\s]*$/g.test(s);
...и тут

2022-09-13 07:21 UTC, deadem commented on src/utils/validation.ts
> +const hasPointAfterAt = (s: string): boolean => /^[^@]*@[^@]+[.]/.test(s);
сейчас email `test@..ru` пройдёт проверку, а не должен, т.к. в нём точка сразу после `@`

2022-09-13 07:21 UTC, deadem commented on src/views/MessageInputView/MessageInputView.scss
> +    ::placeholder {
`&::placeholder`?

2022-09-13 07:21 UTC, deadem commented on .editconfig
> +insert_final_newline = true
не .editconfig, а .editorconfig: https://editorconfig.org/

2022-09-13 07:53 UTC, merged